"""add_items_table

Revision ID: 0c54d8a638b4
Revises: 399e29f73679
Create Date: 2026-05-06 23:55:46.126178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0c54d8a638b4"
down_revision: Union[str, Sequence[str], None] = "399e29f73679"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "items",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("category_name", sa.String(), nullable=True),
        sa.Column("category_image_url", sa.String(), nullable=True),
        sa.Column("leave_at", sa.String(), nullable=True),
        sa.Column("processing", sa.String(), nullable=True),
        sa.Column("last_scraped", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_index(
        "ix_items_name_trgm",
        "items",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_items_name_trgm",
        table_name="items",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("items")
    # ### end Alembic commands ###
