"""add station_type and external_id

Revision ID: 0c8655ec7c9a
Revises: 73dd349a17e1
Create Date: 2026-04-28 15:40:59.709511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c8655ec7c9a'
down_revision: Union[str, Sequence[str], None] = '73dd349a17e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('stations', sa.Column('external_id', sa.String(), nullable=False))
    op.add_column('stations', sa.Column('station_type', sa.String(length=3), nullable=True))
    op.alter_column('sync_meta', 'station_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_meta', 'station_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('stations', 'station_type')
    op.drop_column('stations', 'external_id')
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('email_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
