"""rename_waste_types_to_categories

Revision ID: 399e29f73679
Revises: 4dbc482b3d7a
Create Date: 2026-05-03 20:26:00.958639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "399e29f73679"
down_revision: Union[str, Sequence[str], None] = "4dbc482b3d7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_swt_waste_type"), table_name="station_waste_types")
    op.drop_table("station_waste_types")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_table(
        "station_categories",
        sa.Column("station_id", sa.String(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("station_id", "category_id"),
    )
    op.create_index(
        "ix_swt_waste_type", "station_categories", ["category_id"], unique=False
    )
    op.add_column(
        "status_reports", sa.Column("category_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        "ix_sr_category_id", "status_reports", ["category_id"], unique=False
    )
    op.create_index(
        "ix_sr_unique_active",
        "status_reports",
        ["station_id", "category_id", "user_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "status_reports",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "status_reports", type_="foreignkey") # type:ignore
    op.drop_index("ix_sr_unique_active", table_name="status_reports")
    op.drop_index("ix_sr_category_id", table_name="status_reports")
    op.drop_column("status_reports", "category_id")
    op.create_table(
        "station_waste_types",
        sa.Column("station_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "waste_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("station_waste_types_station_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "station_id", "waste_type", name=op.f("station_waste_types_pkey")
        ),
    )
    op.create_index(
        op.f("ix_swt_waste_type"), "station_waste_types", ["waste_type"], unique=False
    )
    op.drop_index("ix_swt_waste_type", table_name="station_categories")
    op.drop_table("station_categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
