"""add image_url to waste types

Revision ID: 4dbc482b3d7a
Revises: 68fa1fd5906b
Create Date: 2026-04-29 14:20:11.909261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbc482b3d7a'
down_revision: Union[str, Sequence[str], None] = '68fa1fd5906b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_waste_types', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_waste_types', 'image_url')
    # ### end Alembic commands ###
